# Dockerfile.deps
FROM python:3.10-slim

# PyPI 미러 (선택)
RUN pip config set global.index-url https://mirror.kakao.com/pypi/simple

# 작업 디렉토리
WORKDIR /app

# requirements 복사
COPY requirements.txt .

# pip install (캐시 활용)
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -r requirements.txt

# **** 추가된 확인 라인 (빌드 로그에서 설치 여부 확인용) ****
RUN pip show python-jose
# **************************
