name: Build FastAPI Base Image

# requirements.txt 변경 시 또는 수동 트리거로 실행
on:
  push:
    paths:
      - 'fastapi/requirements.txt'
  workflow_dispatch:

env:
  BASE_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app-deps:latest
  APP_IMAGE:  ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
jobs:
  build-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push base image (pip deps)
        uses: docker/build-push-action@v3
        with:
          context: ./fastapi
          file: ./fastapi/Dockerfile.deps
          push: true
          tags: ${{ env.BASE_IMAGE }}
          cache-from: type=registry,ref=${{ env.BASE_IMAGE }}
          cache-to:   type=registry,ref=${{ env.BASE_IMAGE }},mode=max
