name: Deploy FastAPI to Server

on:
  push:
    branches:
      - main

env:
  APP_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push app image (BuildKit off)
        env:
          DOCKER_BUILDKIT: 0     # BuildKit 비활성화
        run: |
          docker build -t ${{ env.APP_IMAGE }} .
          docker push ${{ env.APP_IMAGE }}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: ubuntu
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     22
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" \
              | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            sudo docker rm -f fastapi-app || true
            sudo docker pull ${{ env.APP_IMAGE }}
            sudo docker run -d \
              --name fastapi-app \
              -p 9000:9000 \
              --env-file /home/ubuntu/project/fastapi/.env \
              ${{ env.APP_IMAGE }}
