# .github/workflows/deploy-fastapi.yml
name: Deploy FastAPI to Server

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) pip 캐시 (이미 설치된 패키지 재사용)
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 3) buildx 캐시 디렉터리 복원
      - name: Restore Docker buildx cache
        uses: actions/cache@v3
        with:
          path: .buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile','**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4) Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5) 이미지 빌드 & 푸시 (로컬 + 레지스트리 캐시)
      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          cache-from:
            - type=local,src=.buildx-cache
            - type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to:
            - type=local,dest=.buildx-cache,mode=max
            - type=registry,ref=${{ env.IMAGE_NAME }},mode=max

      # 6) 원격 서버 배포
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: ubuntu
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     22
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" \
              | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            sudo docker rm -f fastapi-app || true

            sudo docker pull ${{ env.IMAGE_NAME }}
            sudo docker run -d \
              --name fastapi-app \
              -p 9000:9000 \
              --env-file /home/ubuntu/project/fastapi/.env \
              ${{ env.IMAGE_NAME }}
